Fixed Steps, added percentage pass threshold

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -34,6 +34,20 @@ jobs:
       env:
         CI: false 
       run: npm run build --if-present
-    - run: npm run build --if-present
-    - name: Run tests
-      run: npm run test
+    - name: Run tests and generate JSON report
+      run: |
+        npm run test -- --json --outputFile=test-report.json
+
+    - name: Calculate pass percentage
+      id: calculate-pass-percentage
+      run: |
+        totalTests=$(jq '.numTotalTests' test-report.json)
+        passedTests=$(jq '.numPassedTests' test-report.json)
+        passPercentage=$((passedTests * 100 / totalTests))
+        echo "Pass Percentage: $passPercentage%"
+
+    - name: Check if pass percentage meets threshold
+      if: env.pass-percentage < 50
+      run: |
+        echo "Test pass percentage is below the threshold. Failing the build."
+        exit 1
